In [36]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity, euclidean_distances, cosine_distances
import text_function as textfun
import pandas as pd
import numpy as np

In [44]:
df = pd.read_excel('Data/example.xlsx')
sentence = df['Sentence']
print(sentence)

0     Leroy Merlin
1     Leroy-Merlin
2    Learoy Meriln
3     Liroy Merlin
Name: Sentence, dtype: object


In [45]:
vectorizer = CountVectorizer(tokenizer=textfun.text_tokenizer)
X_transform = vectorizer.fit_transform(sentence)

In [46]:
cs = cosine_similarity(X_transform, X_transform)
print(cs)

[[1.  0.  0.  0.5]
 [0.  1.  0.  0. ]
 [0.  0.  1.  0. ]
 [0.5 0.  0.  1. ]]


In [48]:

cd = cosine_distances(X_transform, X_transform)
print(cd)

[[0.  1.  1.  0.5]
 [1.  0.  1.  1. ]
 [1.  1.  0.  1. ]
 [0.5 1.  1.  0. ]]


In [47]:
ed = euclidean_distances(X_transform, X_transform)
print(ed)

[[0.         1.73205081 2.         1.41421356]
 [1.73205081 0.         1.73205081 1.73205081]
 [2.         1.73205081 0.         2.        ]
 [1.41421356 1.73205081 2.         0.        ]]


In [29]:
df = pd.read_excel('Data/abba_lyrics.xlsx')
abba = df['Sentence']
print(abba)

0                            You are the dancing queen
1                                      Young and sweet
2                        Only seventeen, Dancing queen
3     I've been cheated by you since I don't know when
4         So I made up my mind, it must come to an end
5                    Look at me now, will I ever learn
6        I don't know how, but I suddenly lose control
7                        There's a fire within my soul
8                           and I can hear a bell ring
9        (One more look) and I forget everything, whoa
10                          Mamma mia, here I go again
11                       My, my, how can I resist you?
12                       Mamma mia, does it show again
13              My, my, just how much I've missed you?
Name: Sentence, dtype: object


In [51]:
vectorizer = CountVectorizer(tokenizer=textfun.text_tokenizer)
X_transform_abba = vectorizer.fit_transform(abba[9:])
# X_transform_array = np.array(X_transform_abba)

In [52]:
cs = cosine_similarity(X_transform_abba, X_transform_abba)
print(cs)

[[1.         0.         0.         0.         0.        ]
 [0.         1.         0.         0.70710678 0.        ]
 [0.         0.         1.         0.         0.        ]
 [0.         0.70710678 0.         1.         0.        ]
 [0.         0.         0.         0.         1.        ]]


In [23]:
dos = ['You are the dancing queen', 'Young and sweet', 'Only seventeen, Dancing queen', "I've been cheated by you since I don't know when"]

vectorizer = CountVectorizer(tokenizer=textfun.text_tokenizer)
dosX_transform = vectorizer.fit_transform(dos)
cs = cosine_similarity(dosX_transform, dosX_transform)
print(cs)

[[1.         0.         0.81649658 0.        ]
 [0.         1.         0.         0.        ]
 [0.81649658 0.         1.         0.        ]
 [0.         0.         0.         1.        ]]
